// Generated by i18n/generate.py from i18n/strings.json -- DO NOT EDIT BY HAND, edit strings.json and re-run that script instead.
#pragma once

namespace strings {

enum class Lang { DE, EN, FR, IT, ES };

extern const char *kAppName;
extern const char *kHostHint;
extern const char *kHostHintExample;
extern const char *kMenuConnect;
extern const char *kMenuSettings;
extern const char *kStatusDisconnected;
extern const char *kStatusConnecting;
extern const char *kStatusHandshake;
extern const char *kStatusConnected;
extern const char *kStatusError;
extern const char *kStatusDisconnectedReason;
extern const char *kStatusConnectFailed;
extern const char *kStatusPhysicalInputActive;
extern const char *kStreamLostTitle;
extern const char *kOk;
extern const char *kCancel;
extern const char *kBack;
extern const char *kClose;
extern const char *kTextInputTitle;
extern const char *kDiscoveryTitle;
extern const char *kDiscoveryStart;
extern const char *kDiscoveryScanning;
extern const char *kDiscoveryNoneFound;
extern const char *kDiscoveryFound;
extern const char *kDiscoveryFoundHeader;
extern const char *kDiscoverySearchingPlaceholder;
extern const char *kDiscoveryIncompatibleSuffix;
extern const char *kDiscoveryIncompatible;
extern const char *kDiscoveryOwnIp;
extern const char *kDiscoveryNoNetwork;
extern const char *kDiscoveryMoreServers;
extern const char *kLobbyHostRequired;
extern const char *kLobbySearching;
extern const char *kLobbyPick;
extern const char *kLobbyPickPlayer;
extern const char *kLobbyNoneFree;
extern const char *kLobbyNoneConfigured;
extern const char *kLobbyHostUnreachable;
extern const char *kLobbySlotOccupied;
extern const char *kLobbySlotFree;
extern const char *kLobbySlotOccupiedTitle;
extern const char *kSettings;
extern const char *kSettingsOnScreenControls;
extern const char *kSettingsAntialiasing;
extern const char *kSettingsVideoMode;
extern const char *kSettingsConsoleSpecific;
extern const char *kVideoModeTiles;
extern const char *kVideoModeH264;
extern const char *kVideoModeH265;
extern const char *kVideoModeLegacy;
extern const char *kVideoModeFallbackTitle;
extern const char *kVideoModeFallbackMessage;
extern const char *kVideoModeFallbackContinue;
extern const char *kVideoModeFallbackAbort;
extern const char *kVideoCodecUnsupported;
extern const char *kSettingsBilinearFilterHeader;
extern const char *kSettingsKeyBindings;
extern const char *kSettingsBind;
extern const char *kSettingsClear;
extern const char *kSettingsUnbound;
extern const char *kSettingsPressKey;
extern const char *kSettingsBottomScreenVideo;
extern const char *kSettingsBottomScreenVideoHint;
extern const char *kSettingsLanguage;
extern const char *kLanguageSystem;
extern const char *kLanguageGerman;
extern const char *kLanguageEnglish;
extern const char *kLanguageFrench;
extern const char *kLanguageItalian;
extern const char *kLanguageSpanish;
extern const char *kConsoleGcGbaLink;
extern const char *kConsoleWiiuGamepad;
extern const char *kConsoleN3dsBottomScreen;
extern const char *kConsoleNdsBottomScreen;
extern const char *kKeyBindingsStandardSection;
extern const char *kKeyBindingsExtendedSection;
extern const char *kKeyBindingsExtendedHint;
extern const char *kKeyBindingsGamepadSection;
extern const char *kKeyBindingsNoGamepad;
extern const char *kKeyBindingsPressButton;
extern const char *kKeyBindingsKeyboardColumn;
extern const char *kKeyBindingsControllerColumn;
extern const char *kExitHoldHint;
extern const char *kDisconnect;
extern const char *kWaitingForImage;
extern const char *kPingLabel;
extern const char *kFpsLabel;
extern const char *kScreenToggle;
extern const char *kScreenTop;
extern const char *kScreenBottom;
extern const char *kScaleToggle;
extern const char *kScaleFill;
extern const char *kScale1to1;
extern const char *kFilterToggle;
extern const char *kFilterOn;
extern const char *kFilterOff;
extern const char *kWifiConnecting;
extern const char *kWifiFailed;
extern const char *kWifiFailedHint;
extern const char *kPressKeyForMenu;
extern const char *kIpPromptTitle;
extern const char *kConnectHintManual;
extern const char *kConnectHintResearch;
extern const char *kConnectHintQuit;
extern const char *kConnectHintSlot;
extern const char *kHandshakeFailed;

// Repoints every constant above at the given language's text --
// call once at startup (after detecting the system language) and
// again whenever the user changes the language setting.
void setLanguage(Lang lang);

} // namespace strings
