#!/usr/bin/env python3
"""Generates each client's UI string resource file from strings.json, the
single source of truth for text shared conceptually across every Unison
client (see strings.json's own top comment for why). Run this after editing
strings.json -- a normal client build never needs to run it, only a change
to strings.json does (same pattern as clients/web/build_wasm.sh regenerating
unison_core.js: the generated output is committed).

Every client picks a language at runtime (system language, English if
undetermined/unsupported, overridable in Settings) -- see each generated
file's own header comment for how that client's setLanguage()/STRINGS
lookup works. A key missing a given language falls back to English at
generation time (see lang_text() below), so a new string can be added in
English only and translated into the rest later without breaking any
client. Android is the one exception: it gets one resource-qualified
directory per language (values/ = English default+fallback, values-de/,
values-fr/, ...) and relies entirely on the OS's own per-key locale
resolution, no runtime switch or explicit fallback needed there.

Usage: i18n/generate.py (no arguments, run from anywhere -- paths are all
relative to this script's own location).
"""
import json
import re
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
STRINGS_JSON = SCRIPT_DIR / "strings.json"

LANGS = ["de", "en", "fr", "it", "es"]
FALLBACK_LANG = "en"


def lang_text(entry, lang):
    return entry.get(lang, entry[FALLBACK_LANG])

HEADER_NOTE = (
    "Generated by i18n/generate.py from i18n/strings.json -- DO NOT EDIT BY "
    "HAND, edit strings.json and re-run that script instead."
)


def load_strings():
    with open(STRINGS_JSON, encoding="utf-8") as f:
        data = json.load(f)
    data.pop("_comment", None)
    return data


# ---------------- Android (strings.xml) ----------------
# Android format strings are positional (%1$s, %2$d, ...) and the XML
# entity-escapes ', ", &, <, > -- apostrophes specifically also need a
# backslash escape even though this is XML, since Android's own resource
# string format additionally treats a bare "'" as a smart-quote trigger.
def android_escape(text):
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    text = text.replace("'", "\\'").replace('"', "&quot;")
    text = text.replace("\n", "\\n")
    return text


def android_format(text, placeholders):
    def repl(m):
        idx = int(m.group(1))
        spec = "d" if placeholders and idx < len(placeholders) and placeholders[idx] == "d" else "s"
        return f"%{idx + 1}${spec}"
    return re.sub(r"\{(\d+)\}", repl, text)


# lang="en" writes the default (qualifier-less) values/ dir -- the dir
# Android falls back to whenever the device locale doesn't match any
# values-<qualifier>/ dir it has (or a values-<qualifier>/ dir it has is
# missing a particular key), which is exactly the "system language
# couldn't be determined, or this key isn't translated yet" behavior asked
# for, entirely via the OS's own per-key resolution -- no explicit
# fallback substitution needed here, unlike every other target below.
def generate_android(strings, lang, dirname):
    lines = ["<resources>"]
    for key, entry in strings.items():
        if lang not in entry:
            continue
        text = android_format(entry[lang], entry.get("placeholders"))
        lines.append(f'    <string name="{key}">{android_escape(text)}</string>')
    lines.append("</resources>")
    lines.append("")
    out = REPO_ROOT / f"clients/android/app/src/main/res/{dirname}/strings.xml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out.relative_to(REPO_ROOT)} ({len(strings)} strings)")


# ---------------- C / C++ (3DS, Switch, NDS) ----------------
# %s/%d in argument order (not positional -- plain printf-family C, no
# %1$s support portable across devkitARM/devkitA64's libc) -- fine here
# since none of these strings reorder their arguments between languages.
def c_escape(text):
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def c_format(text, placeholders):
    def repl(m):
        idx = int(m.group(1))
        spec = "d" if placeholders and idx < len(placeholders) and placeholders[idx] == "d" else "s"
        return f"%{spec}"
    return re.sub(r"\{(\d+)\}", repl, text)


def cpp_name(key):
    return f"k{''.join(part.capitalize() for part in key.split('_'))}"


def c_text(entry, lang):
    return c_escape(c_format(lang_text(entry, lang), entry.get("placeholders")))


# 3DS/Switch: `strings::kFoo` stays a plain `const char *` at every existing
# call site (no call-site changes from the single-language version) --
# what changes is that it's a mutable global instead of a compile-time
# constant, repointed at the current language's text by setLanguage().
# Declared `extern` (not `static`) since Switch's header is #included from
# three separate .cpp files: a `static` global would give each of those its
# own independent copy, and setLanguage() called from just one of them
# wouldn't update the other two's.
def generate_cpp_header(strings, out_path):
    lang_enum = ", ".join(lang.upper() for lang in LANGS)
    lines = [f"// {HEADER_NOTE}", "#pragma once", "", "namespace strings {", "", f"enum class Lang {{ {lang_enum} }};", ""]
    for key in strings:
        lines.append(f"extern const char *{cpp_name(key)};")
    lines.append("")
    lines.append("// Repoints every constant above at the given language's text --")
    lines.append("// call once at startup (after detecting the system language) and")
    lines.append("// again whenever the user changes the language setting.")
    lines.append("void setLanguage(Lang lang);")
    lines.append("")
    lines.append("} // namespace strings")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out_path.relative_to(REPO_ROOT)} ({len(strings)} strings)")


def generate_cpp_source(strings, header_include, out_path):
    lines = [f"// {HEADER_NOTE}", f'#include "{header_include}"', "", "namespace strings {", ""]
    for key, entry in strings.items():
        lines.append(f'const char *{cpp_name(key)} = "{c_text(entry, "de")}";')
    lines.append("")
    lines.append("void setLanguage(Lang lang) {")
    lines.append("    switch (lang) {")
    for lang in LANGS:
        lines.append(f"    case Lang::{lang.upper()}:")
        for key, entry in strings.items():
            lines.append(f'        {cpp_name(key)} = "{c_text(entry, lang)}";')
        lines.append("        break;")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace strings")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out_path.relative_to(REPO_ROOT)} ({len(strings)} strings)")


# NDS: plain C, one header, only ever #included from arm9/source/main.c
# (confirmed -- if a second .c file ever includes this, its STR_FOO
# globals would need to become extern + move into a .c file, same as the
# 3DS/Switch split above). `static` keeps it a drop-in replacement for
# every existing call site.
def generate_nds_header(strings, out_path, macro_guard):
    lines = [f"// {HEADER_NOTE}", f"#ifndef {macro_guard}", f"#define {macro_guard}", ""]
    lang_enum = ", ".join(f"STR_LANG_{lang.upper()}" for lang in LANGS)
    lines.append(f"typedef enum {{ {lang_enum} }} StrLang;")
    lines.append("")
    for key, entry in strings.items():
        name = f"STR_{key.upper()}"
        lines.append(f'static const char *{name} = "{c_text(entry, "de")}";')
    lines.append("")
    lines.append("// Repoints every STR_* constant above at the given language's text --")
    lines.append("// call once at startup (after detecting the system language) and")
    lines.append("// again whenever the user changes the language setting.")
    lines.append("static inline void strSetLanguage(StrLang lang) {")
    lines.append("    switch (lang) {")
    for lang in LANGS:
        lines.append(f"    case STR_LANG_{lang.upper()}:")
        for key, entry in strings.items():
            name = f"STR_{key.upper()}"
            lines.append(f'        {name} = "{c_text(entry, lang)}";')
        lines.append("        break;")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append(f"#endif // {macro_guard}")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out_path.relative_to(REPO_ROOT)} ({len(strings)} strings)")


# ---------------- JS (web) ----------------
# {0}/{1} kept literal -- index.html's own t(key, ...args) helper (see
# strings_generated.js's own header) substitutes them at runtime, same
# placeholder syntax as strings.json itself, no conversion needed.
def js_escape(text):
    return text.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")


def generate_js(strings):
    lines = [f"// {HEADER_NOTE}", "const STRINGS = {"]
    for lang in LANGS:
        lines.append(f"  {lang}: {{")
        for key, entry in strings.items():
            lines.append(f"    {key}: '{js_escape(lang_text(entry, lang))}',")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    out = REPO_ROOT / "clients/web/strings_generated.js"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out.relative_to(REPO_ROOT)} ({len(strings)} strings x {len(LANGS)} langs)")


def main():
    strings = load_strings()

    generate_android(strings, "en", "values")
    for lang in LANGS:
        if lang != "en":
            generate_android(strings, lang, f"values-{lang}")

    generate_cpp_header(strings, REPO_ROOT / "clients/3ds/source/strings_generated.hpp")
    generate_cpp_source(strings, "strings_generated.hpp", REPO_ROOT / "clients/3ds/source/strings_generated.cpp")

    generate_cpp_header(strings, REPO_ROOT / "clients/switch/source/strings_generated.hpp")
    generate_cpp_source(strings, "strings_generated.hpp", REPO_ROOT / "clients/switch/source/strings_generated.cpp")

    generate_nds_header(strings, REPO_ROOT / "clients/nds/arm9/source/strings_generated.h",
                         macro_guard="UNISON_STRINGS_GENERATED_H")

    generate_js(strings)


if __name__ == "__main__":
    main()
