add_executable(finlink_test_protocol test_protocol.c)
target_link_libraries(finlink_test_protocol PRIVATE finlink_core)
add_test(NAME protocol COMMAND finlink_test_protocol)

add_executable(finlink_test_inflate test_inflate.c)
target_link_libraries(finlink_test_inflate PRIVATE finlink_core)
add_test(NAME inflate COMMAND finlink_test_inflate)

add_executable(finlink_test_deflate test_deflate.c)
target_link_libraries(finlink_test_deflate PRIVATE finlink_core)
add_test(NAME deflate COMMAND finlink_test_deflate)

add_executable(finlink_test_websocket test_websocket.c)
target_link_libraries(finlink_test_websocket PRIVATE finlink_core)
add_test(NAME websocket COMMAND finlink_test_websocket)

add_executable(finlink_test_video_encode test_video_encode.c)
target_link_libraries(finlink_test_video_encode PRIVATE finlink_core)
add_test(NAME video_encode COMMAND finlink_test_video_encode)
