add_executable(unison_test_protocol test_protocol.c)
target_link_libraries(unison_test_protocol PRIVATE unison_core)
add_test(NAME protocol COMMAND unison_test_protocol)

add_executable(unison_test_inflate test_inflate.c)
target_link_libraries(unison_test_inflate PRIVATE unison_core)
add_test(NAME inflate COMMAND unison_test_inflate)

add_executable(unison_test_deflate test_deflate.c)
target_link_libraries(unison_test_deflate PRIVATE unison_core)
add_test(NAME deflate COMMAND unison_test_deflate)

add_executable(unison_test_websocket test_websocket.c)
target_link_libraries(unison_test_websocket PRIVATE unison_core)
add_test(NAME websocket COMMAND unison_test_websocket)

add_executable(unison_test_video_encode test_video_encode.c)
target_link_libraries(unison_test_video_encode PRIVATE unison_core)
add_test(NAME video_encode COMMAND unison_test_video_encode)

add_executable(unison_test_handshake test_handshake.c)
target_link_libraries(unison_test_handshake PRIVATE unison_core)
add_test(NAME handshake COMMAND unison_test_handshake)
