import Foundation

/// Resolves Prefs.language ("system"/"de"/"en"/"fr"/"it"/"es") to an actual
/// language tag and looks strings up directly from the matching .lproj
/// bundle (Localizable.strings, generated by i18n/generate.py -- see that
/// script's own comment) rather than the system's automatic
/// NSLocalizedString resolution, since a manual override needs to work
/// regardless of the device's actual system language. Direct port of
/// clients/android/.../LocaleHelper.kt -- see that file's own comment for
/// the full rationale.
enum LocaleHelper {
    // Keep in sync with i18n/strings.json's language set and Prefs.languages.
    private static let supported: Set<String> = ["de", "en", "fr", "it", "es"]

    /// The actual pref/system-language resolution decision, pulled out as
    /// a pure function (not touching Prefs/Bundle) so it has one place to
    /// unit-test -- see LocaleHelperTests. "system" (default, English if
    /// undetermined/unsupported) applies equally to a pref value that
    /// isn't actually one of `supported` (e.g. a stale value from an
    /// older app version's Prefs).
    static func resolveLocaleTag(prefLanguage: String, systemLanguageTag: String) -> String {
        if supported.contains(prefLanguage) { return prefLanguage }
        if supported.contains(systemLanguageTag) { return systemLanguageTag }
        return "en"
    }

    static func resolvedTag(prefs: Prefs) -> String {
        resolveLocaleTag(prefLanguage: prefs.language, systemLanguageTag: systemLanguageTag())
    }

    /// Looks a key up in the resolved language's Localizable.strings
    /// directly (Bundle.path(forResource:), not NSLocalizedString) so the
    /// manual override actually takes effect regardless of the device's
    /// system language. Falls back to the key itself if the bundle/string
    /// is somehow missing (matches every other client's "never crash on a
    /// missing translation" policy).
    static func string(_ key: String, prefs: Prefs) -> String {
        let tag = resolvedTag(prefs: prefs)
        let dirName = tag == "en" ? "Base" : tag
        guard let path = Bundle.main.path(forResource: dirName, ofType: "lproj"),
              let bundle = Bundle(path: path)
        else {
            return key
        }
        return bundle.localizedString(forKey: key, value: key, table: "Localizable")
    }

    private static func systemLanguageTag() -> String {
        Locale.current.language.languageCode?.identifier ?? "en"
    }
}
